package zw.co.learniverse.entities;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.UUID;

@Data
@Embeddable
@Table(uniqueConstraints = @UniqueConstraint(columnNames = "subjectName"))
public class Subjects {


    @Column(nullable = false, updatable = false)
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    private UUID subjectId;
    @NotNull
    private String subjectName;

    // Constructors, getters, and setters are generated by Lombok

    public Subjects(){
        this.subjectId  = UUID.randomUUID();
    }
}